name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.release.target_commitish }}
    - uses: actions/setup-node@v2
      with:
        node-version: lts/*
        registry-url: https://registry.npmjs.org/
    - name: Lint JavaScript source with standard.js
      run: |
        if [ ! -z "$NPM_PROXY" ]; then
          npm --registry=$NPM_PROXY install standard -g
        else
          npm install standard -g
        fi
        standard   
    - name: Configure Git
      run: |
        git config --global user.email "87917386+randomdev1234@users.noreply.github.com"
        git config --global user.name "Github Actions"
    - name: Increase version
      run: npm version patch
    - name: Build web version
      run: npm install && npm install -g expo-cli && expo build:web
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        access: public
    - name: Push changes to Github
      run: git push origin master